export const LOAD_PROFILES = 'LOAD_PROFILES';

export const LOAD_PROFILES_FAILURE = 'LOAD_PROFILES_FAILURE';

export const LOAD_PROFILES_SUCCESS = 'LOAD_PROFILES_SUCCESS';

export const SORT_PROFILES = 'SORT_PROFILES';

