//debts
export const LOAD_PROFILES = 'LOAD_PROFILES';

export const LOAD_PROFILES_FAILURE = 'LOAD_PROFILES_FAILURE';

export const LOAD_PROFILES_SUCCESS = 'LOAD_PROFILES_SUCCESS';

// export const CHANGE_ACCOUNT_TITLE = 'CHANGE_ACCOUNT_TITLE';

export const ADD_DEBT = 'ADD_DEBT';

export const REMOVE_DEBT = 'REMOVE_DEBT';

export const SEND_DEBT_SUCCESS = 'SEND_DEBT_SUCCESS';

//operations
export const LOAD_BILLS = 'LOAD_BILLS';

export const LOAD_BILLS_SUCCESS = 'LOAD_BILLS_SUCCESS';

export const LOAD_BILLS_FAILURE = 'LOAD_BILLS_FAILURE';

export const ADD_BILL = 'ADD_DEBT';
